package com.qacollaboration.enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOT,
    FAILEDSTEPSSCREENSHOT,
    SKIPPEDSTEPSSCREENSHOT,
    RETRYFAILEDTESTS,
    RUNMODE,
    BROWSER,
    SELENIUMGRIDURL
}
